[tool.black]
line-length = 119
exclude = '''
/(
    \.git
  | env
  | __pycache__
  | build
  | dist
  | .*_cache
  | .*\.egg-info
)/
'''


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
  "tests"
]
pythonpath = "."